name: loja_virtual
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  map_launcher: ^2.5.0+1
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.3.0
  firebase_storage: ^11.0.16
  firebase_core: ^2.8.0
  provider: ^6.0.5
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_staggered_grid_view: ^0.6.2
  transparent_image: ^2.0.1
  alphabet_list_scroll_view: ^2.0.0
  faker: ^2.1.0
  image_picker: ^0.8.7+1
  image_cropper: ^3.0.2
  uuid: ^3.0.7
  dio: ^5.1.1
  brasil_fields: ^1.9.1
  geolocator: ^9.0.2
  sliding_up_panel: ^2.0.0+1
  screenshot: ^1.3.0
  image_gallery_saver: '^1.7.1'
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.5
  flip_card: ^0.7.0
  mask_text_input_formatter: ^2.4.0
  credit_card_type_detector: ^3.0.0
  cloud_functions: ^4.1.1
  firebase_messaging: ^14.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
